### ISSUE TITLE
Typing for `identify` method requires `event` prarameter

### ISSUE THREAD

**Issue by DataTables** [PostHog/posthog-node#2]
The [`event` parameter](https://github.com/PostHog/posthog-node/blob/3f88c83ebde108697013422e8004c6f345ea3429/index.d.ts#L22) which is an property option of the `identify` method I think needs to be marked as optional, since it [will default to `$identify`](https://github.com/PostHog/posthog-node/blob/3f88c83ebde108697013422e8004c6f345ea3429/index.js#L78). At the moment TS is throwing an error when not given.

It might be that a second type is needed rather than just marking `event` as option, since it looks like it is not option for the `capture` method.

**Comment by macobo** [comment]
This is now fixed and released 1.0.6. :bow:
