### ISSUE TITLE
Repo out of sync with published version

### ISSUE THREAD

**Issue by jamiehaywood** [PostHog/posthog-node#23]
Our build process is failing during type emission because of a change in the `IdentifyMessage` interface which seems to have been made without changing the `identify()` params signature.

It seems that `event` has been [removed in the source code](https://github.com/PostHog/posthog-node/blob/83938c9f69b0a55881feef3a69a950e5dec5a744/index.d.ts#L49) but has not been published to `v1.0.7`

![image](https://user-images.githubusercontent.com/26779712/118166044-e9d3fc00-b41c-11eb-910a-6e3b94256ad3.png)

verifiable by downloading `v1.0.7` here: https://registry.npmjs.org/posthog-node/-/posthog-node-1.0.7.tgz

which shows that the `index.d.ts` is out of sync with master.

**Comment by timgl** [comment]
Fixed in 1.0.9. Thanks!
