### ISSUE TITLE
error: uncaughtException: Cannot find module './feature-flags'

### ISSUE THREAD

**Issue by anuraagbarde** [PostHog/posthog-node#34]
When I do,
yarn add posthog-node
inside the node_modules/posthog-node the directory structure is like this,
`node_modules
clis.js
event-validation.js
index.d.ts
index.js
LICENSE
package.json
README.md
`

Inside index.js 
`const { FeatureFlagsPoller } = require('./feature-flags')`

there is no './feature-flags' in the folder node_modules/posthog-node/

But here in this Github repo, I see it is there.
How to fix this?

**Comment by yakkomajuri** [comment]
Hey @anuraagbarde! What version of `posthog-node` are you on?

**Comment by anuraagbarde** [comment]
The posthog-node version would be 1.1.0

**Comment by anuraagbarde** [comment]
Also, I manually had to copy the feature-flags.js file into the /node_modules/posthog-node/ folder for it to work.

**Comment by anuraagbarde** [comment]
> https://github.com/PostHog/posthog-node/runs/2774288891?check_suite_focus=true

> 
> npm notice === Tarball Contents === 
> npm notice 1.1kB LICENSE            
> npm notice 1.7kB cli.js             
> npm notice 2.3kB event-validation.js
> npm notice 9.5kB index.js           
> npm notice 1.6kB package.json       
> npm notice 573B  README.md          
> npm notice 4.2kB index.d.ts         


There is no feature-flags.js

**Comment by yakkomajuri** [comment]
Indeed, I downloaded the tarball from GitHub and that was fine, but npm version didn't

Let me try to publish a patch version

**Comment by yakkomajuri** [comment]
cc @Twixes for the workflow

**Comment by yakkomajuri** [comment]
Solved, please update to v1.1.2.

The issue was the files array in `package.json` so @Twixes you can ignore my comment above.
