### ISSUE TITLE
npm install  "no such file or directory, chmod"

### ISSUE THREAD

**Issue by florianherrengt** [PostHog/posthog-node#75]
I am getting an error when trying to `npm install` on CI:

```
npm ERR! enoent ENOENT: no such file or directory, chmod '/node_modules/posthog-node/cli.js'
```

Versions
- Node: 16
- Posthog: 2.0.1

**Comment by SebTVisage** [comment]
Same error here locally. I tried upgrading posthog to 2.0.1 and got this error

**Comment by neilkakkar** [comment]
Thanks for flagging, I'm looking into this now!

**Comment by neilkakkar** [comment]
This should fix it: https://github.com/PostHog/posthog-js-lite/pull/17 - will publish a new version, let me know if you still face issues :)
